package oops;

import java.util.Scanner;



public class CustomExceptionDemo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter value of a: ");
		int a = sc.nextInt();
		System.out.println("Enter value of b: ");
		int b = sc.nextInt();
		int c;
		
		try {
			c = 10/0;
		}
		catch(ArithmeticException e) {
			System.out.println("dfwefwe");
		}
	}

}
